server.port:   8090

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/blogapp?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        enable_lazy_load_no_trans: true
  logging:
    level:
      org.springframework:
       INFO

blogapp:
  properties:
    title: BlogSite
    subtitle: Все обо Всём
    phone: +7 929 591 59155
    email: pavel1119@mail.ru
    copyright: Павел Напреенко
    copyrightFrom: 2021
  settings:
    MULTIUSER_MODE: false
    POST_PREMODERATION: true
    STATISTICS_IS_PUBLIC: true
  captcha:
    code-length: 6
    code-ttl: 1