spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  profiles:
    active: ${PROFILE_ACTIVE:dev}

blogapp:
  properties:
    title: BlogSite
    subtitle: Все обо Всём
    phone: +7 *** 591 5915
    email: pavel1119@mail.ru
    copyright: Павел Напреенко
    copyrightFrom: 2021
  settings:
    MULTIUSER_MODE: false
    POST_PREMODERATION: true
    STATISTICS_IS_PUBLIC: true
  captcha:
    code-length: 6
    code-ttl: 1
  upload-dir:
    location: ${IMAGES_UPLOAD_DIR:upload}
  external-service: ${APPLICATION_EXTERNAL_SERVICE:https://napreenko-java-skillbox.herokuapp.com}

server:
  port: ${PORT:8090}

