server.port:
  8090

spring:

  datasource:
    url:
      jdbc:mysql://localhost:3306/blogapp?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username:
      root
    password:
      admin
    driver-class-name:
      com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout:
        30000
      maximum-pool-size:
        10

  jpa:
    open-in-view:
      false
    generate-ddl:
      true
    hibernate:
      ddl-auto:
        update
      naming:
        implicit-strategy:
          org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy:
          org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql:
      true
    properties:
      hibernate:
        dialect:
          org.hibernate.dialect.MySQL8Dialect
  logging:
    level:
      org.springframework: INFO

blogapp:
  properties:
    title:
      BlogSite
    subtitle:
      Все обо Всём
    phone:
      +7 929 591 59155
    email:
      pavel1119@mail.ru
    copyright:
      Павел Напреенко
    copyrightFrom:
      2021