server.port:  ${PORT:8090}

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    url: jdbc:${JDBC_DATABASE_URL:mysql://localhost:3306/blogapp?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:admin}
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    connection-timeout: 30_000
    maximum-pool-size: 10
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        enable_lazy_load_no_trans: true
  logging:
    level:
      org.springframework: INFO
  mail:
    host: ${MAIL_HOST:smtp.mail.ru}
    username: ${MAIL_USERNAME:sender.sender.sender.sender@mail.ru}
    password: ${MAIL_PASSWORD:NCBnSqwmgpP7VjficJVm}
    port: ${MAIL_PORT:465}
    protocol: ${MAIL_PROTOCOL:smtps}
    test-connection: true
    properties:
      "mail.smtp.auth": true
      "mail.transport.protocol": smtps
      "mail.debug": false

blogapp:
  properties:
    title: BlogSite
    subtitle: Все обо Всём
    phone: +7 *** 591 5915
    email: pavel1119@mail.ru
    copyright: Павел Напреенко
    copyrightFrom: 2021
  settings:
    MULTIUSER_MODE: false
    POST_PREMODERATION: true
    STATISTICS_IS_PUBLIC: true
  captcha:
    code-length: 6
    code-ttl: 1
  upload-dir:
      location: ${IMAGES_UPLOAD_DIR:upload}

